remote_theme: hydecorp/hydejack@v9.2.1

title: Exploring watercolors with Pietro
description: A short description of your site (~150 chars)

url: https://pietrolc.github.io/
baseurl: /watercolors

lang: en # Language of your content

# A shorter description for the sidebar.
tagline: My artistic portfolio

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/logo.png

defaults:
  - scope:
      type: posts
    values:
      comments: false

# Author Information
author:
  name: Your Name
  email: your@email.com
  about: |
    This is a brief bio about you.
    You can add multiple paragraphs here.
  
  youtube: https://www.youtube.com/@PietroLCWatercolours
  instagram: https://www.instagram.com/pietrowatercolor
    
    # This photo will be used in the about section
  picture:
    path:            https://via.placeholder.com/128x128
    # srcset is optional, but can be used to provide higher res versions for retina displays
    srcset:
      1x:            https://via.placeholder.com/128x128
      2x:            https://via.placeholder.com/256x256

# Menu Configuration
menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/

accent_image: /assets/img/pexels-zaksheuskaya-709412-1568607.jpg
accent_color: rgb(79,177,186)

theme_color:  rgb(25,55,71)

timezone: Europe/Rome

paginate:      10
paginate_path: '/:num/'

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2025. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

hydejack:
  dark_mode:
    dynamic: true
    icon:    true
    always:  false
    
# Analytics
analytics:
  provider: goatcounter
  goatcounter:
    code: pwc # Replace with your GoatCounter code
    
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - LICENSE
  
advertise:           false

