remote_theme: hydecorp/hydejack@v9.2.1

url: https://pietrolc.github.io/
baseurl: /watercolors

accent_image: /assets/img/pexels-zaksheuskaya-709412-1568607.jpg
accent_color: rgb(79,177,186)

theme_color:  rgb(25,55,71)

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

paginate:      10
paginate_path: '/:num/'

hydejack:
  dark_mode:
    dynamic: true
    icon:    true
    always:  false
